apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-app
  template:
    metadata:
      labels:
        app: analytics-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      tolerations:
      - key: "analytics"
        operator: "Equal"
        value: "strict"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "role"
                operator: In
                values:
                - analytics

      containers:
      - name: analytics-app-container
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
