apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
subjects:
- kind: ServiceAccount
  name: app-reader-sa
roleRef:
  kind: Role
  name: app-reader-role
  apiGroup: rbac.authorization.k8s.io