apiVersion: v1 
kind: Pod
metadata:
  name: app-frontend
  labels:
    tier: frontend
spec:
  containers:
  - name: app-frontend-container
    image: nginx


---
apiVersion: v1 
kind: Pod
metadata:
  name: app-backend
  labels:
    tier: backend
spec:
  containers:
  - name: app-backend-container
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: app-database
  labels:
    tier: database
spec:
  containers:
  - name: app-database-container
    image: nginx