apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/share/emptydir
    - name: app-2
      image: nginx
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/share/emptydir-2
  volumes:
    - name: emptydir-volume
      emptyDir: {}