apiVersion: v1 
kind: Pod
metadata:
  name: kubectl-pod
spec:
  serviceAccountName: app-reader-sa
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]

  