apiVersion: v1 
kind: LimitRange
metadata:
  name: dev-limits
  namespace: development
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "64Mi"
    min:
      cpu: "50m"
      memory: "32Mi"
    max:
      cpu: "1000m"
      memory: "512Mi"