apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemonset
  namespace: monitoring
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.35
        ports:
        - containerPort: 8080
        command: ["sleep", "3600"]