apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
  
