apiVersion: v1 
kind: Pod
metadata:
  name: nginx-no-toleration
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80 

  
  