apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80

    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 3
      failureThreshold: 10

    livenessProbe:
      httpGet:
        path: /
        port: 80  
      periodSeconds: 15
      failureThreshold: 2
      timeoutSeconds: 5

    readinessProbe:
      httpGet:  
        path: /
        port: 80
      periodSeconds: 10