apiVersion: v1 
kind: Pod
metadata:
  name: nginx-with-toleration
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80