apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    tier: fast
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    tier: standard
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data/pv2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  labels:
    tier: slow
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pv3