apiVersion: v1 
kind: Pod
metadata:
  name: redis-cache
spec:
  containers:
  - name: redis
    image: redis:7-alpine 
    ports:
    - containerPort: 6379 
  resources:
    requests:
      memory: "200Mi"
      cpu: "50m"
    limits:
      memory: "400Mi"
      cpu: "200m"
    