apiVersion: v1
kind: Secret
metadata:
  name: app-secrets 
type: Opaque
data:
  DB_USERNAME: bXlzcWwtdXNlcg==  
  DB_PASSWORD: c2VjdXJlLXBhc3M= 
  API_KEY: YXBpLWtlLXNlY3JldA==  
  JWT_TOKEN: bXlqd3QtdG9rZW4=

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: [ "sh", "-c", "env; sleep 3600" ]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        - name: JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_TOKEN

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: [ "sh", "-c", "cat /etc/secrets/db_username; sleep 3600" ]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secrets 