apiVersion: v1
kind: Service
metadata:
  name: web-svc-nodeport
spec:
  type: NodePort
  selector:
    app: web-nodeport
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080